package http;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitoringFile.proto

public final class MonitoringFileEntity {
  private MonitoringFileEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MonitoringFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MonitoringFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *���ID
     * </pre>
     *
     * <code>string tunnelId = 1;</code>
     */
    String getTunnelId();
    /**
     * <pre>
     *���ID
     * </pre>
     *
     * <code>string tunnelId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTunnelIdBytes();

    /**
     * <pre>
     *�����ӵ�����ID
     * </pre>
     *
     * <code>string galleryId = 2;</code>
     */
    String getGalleryId();
    /**
     * <pre>
     *�����ӵ�����ID
     * </pre>
     *
     * <code>string galleryId = 2;</code>
     */
    com.google.protobuf.ByteString
        getGalleryIdBytes();

    /**
     * <pre>
     *��վ����
     * </pre>
     *
     * <code>string siteName = 3;</code>
     */
    String getSiteName();
    /**
     * <pre>
     *��վ����
     * </pre>
     *
     * <code>string siteName = 3;</code>
     */
    com.google.protobuf.ByteString
        getSiteNameBytes();

    /**
     * <pre>
     *���ǰ׺
     * </pre>
     *
     * <code>string mileagePrefix = 4;</code>
     */
    String getMileagePrefix();
    /**
     * <pre>
     *���ǰ׺
     * </pre>
     *
     * <code>string mileagePrefix = 4;</code>
     */
    com.google.protobuf.ByteString
        getMileagePrefixBytes();

    /**
     * <pre>
     *��ʼ���
     * </pre>
     *
     * <code>string startLegend = 5;</code>
     */
    String getStartLegend();
    /**
     * <pre>
     *��ʼ���
     * </pre>
     *
     * <code>string startLegend = 5;</code>
     */
    com.google.protobuf.ByteString
        getStartLegendBytes();

    /**
     * <pre>
     *��ֹ���
     * </pre>
     *
     * <code>string endLegend = 6;</code>
     */
    String getEndLegend();
    /**
     * <pre>
     *��ֹ���
     * </pre>
     *
     * <code>string endLegend = 6;</code>
     */
    com.google.protobuf.ByteString
        getEndLegendBytes();

    /**
     * <pre>
     *����ֿ�����
     * </pre>
     *
     * <code>int32 numOfSection = 7;</code>
     */
    int getNumOfSection();

    /**
     * <pre>
     *��������
     * </pre>
     *
     * <code>double rectLegend = 8;</code>
     */
    double getRectLegend();

    /**
     * <pre>
     *���ʱ��
     * </pre>
     *
     * <code>string monitoringTime = 9;</code>
     */
    String getMonitoringTime();
    /**
     * <pre>
     *���ʱ��
     * </pre>
     *
     * <code>string monitoringTime = 9;</code>
     */
    com.google.protobuf.ByteString
        getMonitoringTimeBytes();

    /**
     * <pre>
     *�ļ�����
     * </pre>
     *
     * <code>int32 filesNum = 10;</code>
     */
    int getFilesNum();

    /**
     * <pre>
     *ɨ����������
     * </pre>
     *
     * <code>string scanDataType = 11;</code>
     */
    String getScanDataType();
    /**
     * <pre>
     *ɨ����������
     * </pre>
     *
     * <code>string scanDataType = 11;</code>
     */
    com.google.protobuf.ByteString
        getScanDataTypeBytes();

    /**
     * <pre>
     *�ļ���������ļ����
     * </pre>
     *
     * <code>repeated string filesName = 12;</code>
     */
    java.util.List<String>
        getFilesNameList();
    /**
     * <pre>
     *�ļ���������ļ����
     * </pre>
     *
     * <code>repeated string filesName = 12;</code>
     */
    int getFilesNameCount();
    /**
     * <pre>
     *�ļ���������ļ����
     * </pre>
     *
     * <code>repeated string filesName = 12;</code>
     */
    String getFilesName(int index);
    /**
     * <pre>
     *�ļ���������ļ����
     * </pre>
     *
     * <code>repeated string filesName = 12;</code>
     */
    com.google.protobuf.ByteString
        getFilesNameBytes(int index);

    /**
     * <pre>
     *����ļ�
     * </pre>
     *
     * <code>repeated bytes files = 13;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getFilesList();
    /**
     * <pre>
     *����ļ�
     * </pre>
     *
     * <code>repeated bytes files = 13;</code>
     */
    int getFilesCount();
    /**
     * <pre>
     *����ļ�
     * </pre>
     *
     * <code>repeated bytes files = 13;</code>
     */
    com.google.protobuf.ByteString getFiles(int index);
  }
  /**
   * Protobuf type {@code MonitoringFile}
   */
  public  static final class MonitoringFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MonitoringFile)
      MonitoringFileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MonitoringFile.newBuilder() to construct.
    private MonitoringFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MonitoringFile() {
      tunnelId_ = "";
      galleryId_ = "";
      siteName_ = "";
      mileagePrefix_ = "";
      startLegend_ = "";
      endLegend_ = "";
      monitoringTime_ = "";
      scanDataType_ = "";
      filesName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      files_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MonitoringFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              tunnelId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              galleryId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              siteName_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              mileagePrefix_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              startLegend_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              endLegend_ = s;
              break;
            }
            case 56: {

              numOfSection_ = input.readInt32();
              break;
            }
            case 65: {

              rectLegend_ = input.readDouble();
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              monitoringTime_ = s;
              break;
            }
            case 80: {

              filesNum_ = input.readInt32();
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              scanDataType_ = s;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000800) != 0)) {
                filesName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000800;
              }
              filesName_.add(s);
              break;
            }
            case 106: {
              if (!((mutable_bitField0_ & 0x00001000) != 0)) {
                files_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00001000;
              }
              files_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000800) != 0)) {
          filesName_ = filesName_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00001000) != 0)) {
          files_ = java.util.Collections.unmodifiableList(files_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MonitoringFileEntity.internal_static_MonitoringFile_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MonitoringFileEntity.internal_static_MonitoringFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MonitoringFile.class, Builder.class);
    }

    private int bitField0_;
    public static final int TUNNELID_FIELD_NUMBER = 1;
    private volatile Object tunnelId_;
    /**
     * <pre>
     *���ID
     * </pre>
     *
     * <code>string tunnelId = 1;</code>
     */
    public String getTunnelId() {
      Object ref = tunnelId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tunnelId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *���ID
     * </pre>
     *
     * <code>string tunnelId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTunnelIdBytes() {
      Object ref = tunnelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tunnelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GALLERYID_FIELD_NUMBER = 2;
    private volatile Object galleryId_;
    /**
     * <pre>
     *�����ӵ�����ID
     * </pre>
     *
     * <code>string galleryId = 2;</code>
     */
    public String getGalleryId() {
      Object ref = galleryId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        galleryId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *�����ӵ�����ID
     * </pre>
     *
     * <code>string galleryId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGalleryIdBytes() {
      Object ref = galleryId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        galleryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SITENAME_FIELD_NUMBER = 3;
    private volatile Object siteName_;
    /**
     * <pre>
     *��վ����
     * </pre>
     *
     * <code>string siteName = 3;</code>
     */
    public String getSiteName() {
      Object ref = siteName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        siteName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��վ����
     * </pre>
     *
     * <code>string siteName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSiteNameBytes() {
      Object ref = siteName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        siteName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MILEAGEPREFIX_FIELD_NUMBER = 4;
    private volatile Object mileagePrefix_;
    /**
     * <pre>
     *���ǰ׺
     * </pre>
     *
     * <code>string mileagePrefix = 4;</code>
     */
    public String getMileagePrefix() {
      Object ref = mileagePrefix_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mileagePrefix_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *���ǰ׺
     * </pre>
     *
     * <code>string mileagePrefix = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMileagePrefixBytes() {
      Object ref = mileagePrefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mileagePrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTLEGEND_FIELD_NUMBER = 5;
    private volatile Object startLegend_;
    /**
     * <pre>
     *��ʼ���
     * </pre>
     *
     * <code>string startLegend = 5;</code>
     */
    public String getStartLegend() {
      Object ref = startLegend_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        startLegend_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��ʼ���
     * </pre>
     *
     * <code>string startLegend = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStartLegendBytes() {
      Object ref = startLegend_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        startLegend_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDLEGEND_FIELD_NUMBER = 6;
    private volatile Object endLegend_;
    /**
     * <pre>
     *��ֹ���
     * </pre>
     *
     * <code>string endLegend = 6;</code>
     */
    public String getEndLegend() {
      Object ref = endLegend_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        endLegend_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��ֹ���
     * </pre>
     *
     * <code>string endLegend = 6;</code>
     */
    public com.google.protobuf.ByteString
        getEndLegendBytes() {
      Object ref = endLegend_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        endLegend_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMOFSECTION_FIELD_NUMBER = 7;
    private int numOfSection_;
    /**
     * <pre>
     *����ֿ�����
     * </pre>
     *
     * <code>int32 numOfSection = 7;</code>
     */
    public int getNumOfSection() {
      return numOfSection_;
    }

    public static final int RECTLEGEND_FIELD_NUMBER = 8;
    private double rectLegend_;
    /**
     * <pre>
     *��������
     * </pre>
     *
     * <code>double rectLegend = 8;</code>
     */
    public double getRectLegend() {
      return rectLegend_;
    }

    public static final int MONITORINGTIME_FIELD_NUMBER = 9;
    private volatile Object monitoringTime_;
    /**
     * <pre>
     *���ʱ��
     * </pre>
     *
     * <code>string monitoringTime = 9;</code>
     */
    public String getMonitoringTime() {
      Object ref = monitoringTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        monitoringTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *���ʱ��
     * </pre>
     *
     * <code>string monitoringTime = 9;</code>
     */
    public com.google.protobuf.ByteString
        getMonitoringTimeBytes() {
      Object ref = monitoringTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        monitoringTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILESNUM_FIELD_NUMBER = 10;
    private int filesNum_;
    /**
     * <pre>
     *�ļ�����
     * </pre>
     *
     * <code>int32 filesNum = 10;</code>
     */
    public int getFilesNum() {
      return filesNum_;
    }

    public static final int SCANDATATYPE_FIELD_NUMBER = 11;
    private volatile Object scanDataType_;
    /**
     * <pre>
     *ɨ����������
     * </pre>
     *
     * <code>string scanDataType = 11;</code>
     */
    public String getScanDataType() {
      Object ref = scanDataType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        scanDataType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *ɨ����������
     * </pre>
     *
     * <code>string scanDataType = 11;</code>
     */
    public com.google.protobuf.ByteString
        getScanDataTypeBytes() {
      Object ref = scanDataType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        scanDataType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILESNAME_FIELD_NUMBER = 12;
    private com.google.protobuf.LazyStringList filesName_;
    /**
     * <pre>
     *�ļ���������ļ����
     * </pre>
     *
     * <code>repeated string filesName = 12;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFilesNameList() {
      return filesName_;
    }
    /**
     * <pre>
     *�ļ���������ļ����
     * </pre>
     *
     * <code>repeated string filesName = 12;</code>
     */
    public int getFilesNameCount() {
      return filesName_.size();
    }
    /**
     * <pre>
     *�ļ���������ļ����
     * </pre>
     *
     * <code>repeated string filesName = 12;</code>
     */
    public String getFilesName(int index) {
      return filesName_.get(index);
    }
    /**
     * <pre>
     *�ļ���������ļ����
     * </pre>
     *
     * <code>repeated string filesName = 12;</code>
     */
    public com.google.protobuf.ByteString
        getFilesNameBytes(int index) {
      return filesName_.getByteString(index);
    }

    public static final int FILES_FIELD_NUMBER = 13;
    private java.util.List<com.google.protobuf.ByteString> files_;
    /**
     * <pre>
     *����ļ�
     * </pre>
     *
     * <code>repeated bytes files = 13;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getFilesList() {
      return files_;
    }
    /**
     * <pre>
     *����ļ�
     * </pre>
     *
     * <code>repeated bytes files = 13;</code>
     */
    public int getFilesCount() {
      return files_.size();
    }
    /**
     * <pre>
     *����ļ�
     * </pre>
     *
     * <code>repeated bytes files = 13;</code>
     */
    public com.google.protobuf.ByteString getFiles(int index) {
      return files_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTunnelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tunnelId_);
      }
      if (!getGalleryIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, galleryId_);
      }
      if (!getSiteNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, siteName_);
      }
      if (!getMileagePrefixBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mileagePrefix_);
      }
      if (!getStartLegendBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, startLegend_);
      }
      if (!getEndLegendBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, endLegend_);
      }
      if (numOfSection_ != 0) {
        output.writeInt32(7, numOfSection_);
      }
      if (rectLegend_ != 0D) {
        output.writeDouble(8, rectLegend_);
      }
      if (!getMonitoringTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, monitoringTime_);
      }
      if (filesNum_ != 0) {
        output.writeInt32(10, filesNum_);
      }
      if (!getScanDataTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, scanDataType_);
      }
      for (int i = 0; i < filesName_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, filesName_.getRaw(i));
      }
      for (int i = 0; i < files_.size(); i++) {
        output.writeBytes(13, files_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTunnelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tunnelId_);
      }
      if (!getGalleryIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, galleryId_);
      }
      if (!getSiteNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, siteName_);
      }
      if (!getMileagePrefixBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mileagePrefix_);
      }
      if (!getStartLegendBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, startLegend_);
      }
      if (!getEndLegendBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, endLegend_);
      }
      if (numOfSection_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, numOfSection_);
      }
      if (rectLegend_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, rectLegend_);
      }
      if (!getMonitoringTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, monitoringTime_);
      }
      if (filesNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, filesNum_);
      }
      if (!getScanDataTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, scanDataType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < filesName_.size(); i++) {
          dataSize += computeStringSizeNoTag(filesName_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFilesNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < files_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(files_.get(i));
        }
        size += dataSize;
        size += 1 * getFilesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MonitoringFile)) {
        return super.equals(obj);
      }
      MonitoringFile other = (MonitoringFile) obj;

      if (!getTunnelId()
          .equals(other.getTunnelId())) return false;
      if (!getGalleryId()
          .equals(other.getGalleryId())) return false;
      if (!getSiteName()
          .equals(other.getSiteName())) return false;
      if (!getMileagePrefix()
          .equals(other.getMileagePrefix())) return false;
      if (!getStartLegend()
          .equals(other.getStartLegend())) return false;
      if (!getEndLegend()
          .equals(other.getEndLegend())) return false;
      if (getNumOfSection()
          != other.getNumOfSection()) return false;
      if (Double.doubleToLongBits(getRectLegend())
          != Double.doubleToLongBits(
              other.getRectLegend())) return false;
      if (!getMonitoringTime()
          .equals(other.getMonitoringTime())) return false;
      if (getFilesNum()
          != other.getFilesNum()) return false;
      if (!getScanDataType()
          .equals(other.getScanDataType())) return false;
      if (!getFilesNameList()
          .equals(other.getFilesNameList())) return false;
      if (!getFilesList()
          .equals(other.getFilesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TUNNELID_FIELD_NUMBER;
      hash = (53 * hash) + getTunnelId().hashCode();
      hash = (37 * hash) + GALLERYID_FIELD_NUMBER;
      hash = (53 * hash) + getGalleryId().hashCode();
      hash = (37 * hash) + SITENAME_FIELD_NUMBER;
      hash = (53 * hash) + getSiteName().hashCode();
      hash = (37 * hash) + MILEAGEPREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getMileagePrefix().hashCode();
      hash = (37 * hash) + STARTLEGEND_FIELD_NUMBER;
      hash = (53 * hash) + getStartLegend().hashCode();
      hash = (37 * hash) + ENDLEGEND_FIELD_NUMBER;
      hash = (53 * hash) + getEndLegend().hashCode();
      hash = (37 * hash) + NUMOFSECTION_FIELD_NUMBER;
      hash = (53 * hash) + getNumOfSection();
      hash = (37 * hash) + RECTLEGEND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getRectLegend()));
      hash = (37 * hash) + MONITORINGTIME_FIELD_NUMBER;
      hash = (53 * hash) + getMonitoringTime().hashCode();
      hash = (37 * hash) + FILESNUM_FIELD_NUMBER;
      hash = (53 * hash) + getFilesNum();
      hash = (37 * hash) + SCANDATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getScanDataType().hashCode();
      if (getFilesNameCount() > 0) {
        hash = (37 * hash) + FILESNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFilesNameList().hashCode();
      }
      if (getFilesCount() > 0) {
        hash = (37 * hash) + FILES_FIELD_NUMBER;
        hash = (53 * hash) + getFilesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MonitoringFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonitoringFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonitoringFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonitoringFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonitoringFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonitoringFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonitoringFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MonitoringFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MonitoringFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MonitoringFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MonitoringFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MonitoringFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MonitoringFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MonitoringFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MonitoringFile)
        MonitoringFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MonitoringFileEntity.internal_static_MonitoringFile_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MonitoringFileEntity.internal_static_MonitoringFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MonitoringFile.class, Builder.class);
      }

      // Construct using MonitoringFileEntity.MonitoringFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        tunnelId_ = "";

        galleryId_ = "";

        siteName_ = "";

        mileagePrefix_ = "";

        startLegend_ = "";

        endLegend_ = "";

        numOfSection_ = 0;

        rectLegend_ = 0D;

        monitoringTime_ = "";

        filesNum_ = 0;

        scanDataType_ = "";

        filesName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000800);
        files_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MonitoringFileEntity.internal_static_MonitoringFile_descriptor;
      }

      @Override
      public MonitoringFile getDefaultInstanceForType() {
        return MonitoringFile.getDefaultInstance();
      }

      @Override
      public MonitoringFile build() {
        MonitoringFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MonitoringFile buildPartial() {
        MonitoringFile result = new MonitoringFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.tunnelId_ = tunnelId_;
        result.galleryId_ = galleryId_;
        result.siteName_ = siteName_;
        result.mileagePrefix_ = mileagePrefix_;
        result.startLegend_ = startLegend_;
        result.endLegend_ = endLegend_;
        result.numOfSection_ = numOfSection_;
        result.rectLegend_ = rectLegend_;
        result.monitoringTime_ = monitoringTime_;
        result.filesNum_ = filesNum_;
        result.scanDataType_ = scanDataType_;
        if (((bitField0_ & 0x00000800) != 0)) {
          filesName_ = filesName_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000800);
        }
        result.filesName_ = filesName_;
        if (((bitField0_ & 0x00001000) != 0)) {
          files_ = java.util.Collections.unmodifiableList(files_);
          bitField0_ = (bitField0_ & ~0x00001000);
        }
        result.files_ = files_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MonitoringFile) {
          return mergeFrom((MonitoringFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MonitoringFile other) {
        if (other == MonitoringFile.getDefaultInstance()) return this;
        if (!other.getTunnelId().isEmpty()) {
          tunnelId_ = other.tunnelId_;
          onChanged();
        }
        if (!other.getGalleryId().isEmpty()) {
          galleryId_ = other.galleryId_;
          onChanged();
        }
        if (!other.getSiteName().isEmpty()) {
          siteName_ = other.siteName_;
          onChanged();
        }
        if (!other.getMileagePrefix().isEmpty()) {
          mileagePrefix_ = other.mileagePrefix_;
          onChanged();
        }
        if (!other.getStartLegend().isEmpty()) {
          startLegend_ = other.startLegend_;
          onChanged();
        }
        if (!other.getEndLegend().isEmpty()) {
          endLegend_ = other.endLegend_;
          onChanged();
        }
        if (other.getNumOfSection() != 0) {
          setNumOfSection(other.getNumOfSection());
        }
        if (other.getRectLegend() != 0D) {
          setRectLegend(other.getRectLegend());
        }
        if (!other.getMonitoringTime().isEmpty()) {
          monitoringTime_ = other.monitoringTime_;
          onChanged();
        }
        if (other.getFilesNum() != 0) {
          setFilesNum(other.getFilesNum());
        }
        if (!other.getScanDataType().isEmpty()) {
          scanDataType_ = other.scanDataType_;
          onChanged();
        }
        if (!other.filesName_.isEmpty()) {
          if (filesName_.isEmpty()) {
            filesName_ = other.filesName_;
            bitField0_ = (bitField0_ & ~0x00000800);
          } else {
            ensureFilesNameIsMutable();
            filesName_.addAll(other.filesName_);
          }
          onChanged();
        }
        if (!other.files_.isEmpty()) {
          if (files_.isEmpty()) {
            files_ = other.files_;
            bitField0_ = (bitField0_ & ~0x00001000);
          } else {
            ensureFilesIsMutable();
            files_.addAll(other.files_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MonitoringFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MonitoringFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object tunnelId_ = "";
      /**
       * <pre>
       *���ID
       * </pre>
       *
       * <code>string tunnelId = 1;</code>
       */
      public String getTunnelId() {
        Object ref = tunnelId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tunnelId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *���ID
       * </pre>
       *
       * <code>string tunnelId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTunnelIdBytes() {
        Object ref = tunnelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tunnelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *���ID
       * </pre>
       *
       * <code>string tunnelId = 1;</code>
       */
      public Builder setTunnelId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        tunnelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *���ID
       * </pre>
       *
       * <code>string tunnelId = 1;</code>
       */
      public Builder clearTunnelId() {

        tunnelId_ = getDefaultInstance().getTunnelId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *���ID
       * </pre>
       *
       * <code>string tunnelId = 1;</code>
       */
      public Builder setTunnelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        tunnelId_ = value;
        onChanged();
        return this;
      }

      private Object galleryId_ = "";
      /**
       * <pre>
       *�����ӵ�����ID
       * </pre>
       *
       * <code>string galleryId = 2;</code>
       */
      public String getGalleryId() {
        Object ref = galleryId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          galleryId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *�����ӵ�����ID
       * </pre>
       *
       * <code>string galleryId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGalleryIdBytes() {
        Object ref = galleryId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          galleryId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *�����ӵ�����ID
       * </pre>
       *
       * <code>string galleryId = 2;</code>
       */
      public Builder setGalleryId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        galleryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�����ӵ�����ID
       * </pre>
       *
       * <code>string galleryId = 2;</code>
       */
      public Builder clearGalleryId() {

        galleryId_ = getDefaultInstance().getGalleryId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�����ӵ�����ID
       * </pre>
       *
       * <code>string galleryId = 2;</code>
       */
      public Builder setGalleryIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        galleryId_ = value;
        onChanged();
        return this;
      }

      private Object siteName_ = "";
      /**
       * <pre>
       *��վ����
       * </pre>
       *
       * <code>string siteName = 3;</code>
       */
      public String getSiteName() {
        Object ref = siteName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          siteName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��վ����
       * </pre>
       *
       * <code>string siteName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSiteNameBytes() {
        Object ref = siteName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          siteName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��վ����
       * </pre>
       *
       * <code>string siteName = 3;</code>
       */
      public Builder setSiteName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        siteName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��վ����
       * </pre>
       *
       * <code>string siteName = 3;</code>
       */
      public Builder clearSiteName() {

        siteName_ = getDefaultInstance().getSiteName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��վ����
       * </pre>
       *
       * <code>string siteName = 3;</code>
       */
      public Builder setSiteNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        siteName_ = value;
        onChanged();
        return this;
      }

      private Object mileagePrefix_ = "";
      /**
       * <pre>
       *���ǰ׺
       * </pre>
       *
       * <code>string mileagePrefix = 4;</code>
       */
      public String getMileagePrefix() {
        Object ref = mileagePrefix_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mileagePrefix_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *���ǰ׺
       * </pre>
       *
       * <code>string mileagePrefix = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMileagePrefixBytes() {
        Object ref = mileagePrefix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mileagePrefix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *���ǰ׺
       * </pre>
       *
       * <code>string mileagePrefix = 4;</code>
       */
      public Builder setMileagePrefix(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        mileagePrefix_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *���ǰ׺
       * </pre>
       *
       * <code>string mileagePrefix = 4;</code>
       */
      public Builder clearMileagePrefix() {

        mileagePrefix_ = getDefaultInstance().getMileagePrefix();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *���ǰ׺
       * </pre>
       *
       * <code>string mileagePrefix = 4;</code>
       */
      public Builder setMileagePrefixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        mileagePrefix_ = value;
        onChanged();
        return this;
      }

      private Object startLegend_ = "";
      /**
       * <pre>
       *��ʼ���
       * </pre>
       *
       * <code>string startLegend = 5;</code>
       */
      public String getStartLegend() {
        Object ref = startLegend_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          startLegend_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��ʼ���
       * </pre>
       *
       * <code>string startLegend = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStartLegendBytes() {
        Object ref = startLegend_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          startLegend_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��ʼ���
       * </pre>
       *
       * <code>string startLegend = 5;</code>
       */
      public Builder setStartLegend(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        startLegend_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��ʼ���
       * </pre>
       *
       * <code>string startLegend = 5;</code>
       */
      public Builder clearStartLegend() {

        startLegend_ = getDefaultInstance().getStartLegend();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��ʼ���
       * </pre>
       *
       * <code>string startLegend = 5;</code>
       */
      public Builder setStartLegendBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        startLegend_ = value;
        onChanged();
        return this;
      }

      private Object endLegend_ = "";
      /**
       * <pre>
       *��ֹ���
       * </pre>
       *
       * <code>string endLegend = 6;</code>
       */
      public String getEndLegend() {
        Object ref = endLegend_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          endLegend_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��ֹ���
       * </pre>
       *
       * <code>string endLegend = 6;</code>
       */
      public com.google.protobuf.ByteString
          getEndLegendBytes() {
        Object ref = endLegend_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          endLegend_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��ֹ���
       * </pre>
       *
       * <code>string endLegend = 6;</code>
       */
      public Builder setEndLegend(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        endLegend_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��ֹ���
       * </pre>
       *
       * <code>string endLegend = 6;</code>
       */
      public Builder clearEndLegend() {

        endLegend_ = getDefaultInstance().getEndLegend();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��ֹ���
       * </pre>
       *
       * <code>string endLegend = 6;</code>
       */
      public Builder setEndLegendBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        endLegend_ = value;
        onChanged();
        return this;
      }

      private int numOfSection_ ;
      /**
       * <pre>
       *����ֿ�����
       * </pre>
       *
       * <code>int32 numOfSection = 7;</code>
       */
      public int getNumOfSection() {
        return numOfSection_;
      }
      /**
       * <pre>
       *����ֿ�����
       * </pre>
       *
       * <code>int32 numOfSection = 7;</code>
       */
      public Builder setNumOfSection(int value) {

        numOfSection_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *����ֿ�����
       * </pre>
       *
       * <code>int32 numOfSection = 7;</code>
       */
      public Builder clearNumOfSection() {

        numOfSection_ = 0;
        onChanged();
        return this;
      }

      private double rectLegend_ ;
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>double rectLegend = 8;</code>
       */
      public double getRectLegend() {
        return rectLegend_;
      }
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>double rectLegend = 8;</code>
       */
      public Builder setRectLegend(double value) {

        rectLegend_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>double rectLegend = 8;</code>
       */
      public Builder clearRectLegend() {

        rectLegend_ = 0D;
        onChanged();
        return this;
      }

      private Object monitoringTime_ = "";
      /**
       * <pre>
       *���ʱ��
       * </pre>
       *
       * <code>string monitoringTime = 9;</code>
       */
      public String getMonitoringTime() {
        Object ref = monitoringTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          monitoringTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *���ʱ��
       * </pre>
       *
       * <code>string monitoringTime = 9;</code>
       */
      public com.google.protobuf.ByteString
          getMonitoringTimeBytes() {
        Object ref = monitoringTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          monitoringTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *���ʱ��
       * </pre>
       *
       * <code>string monitoringTime = 9;</code>
       */
      public Builder setMonitoringTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        monitoringTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *���ʱ��
       * </pre>
       *
       * <code>string monitoringTime = 9;</code>
       */
      public Builder clearMonitoringTime() {

        monitoringTime_ = getDefaultInstance().getMonitoringTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *���ʱ��
       * </pre>
       *
       * <code>string monitoringTime = 9;</code>
       */
      public Builder setMonitoringTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        monitoringTime_ = value;
        onChanged();
        return this;
      }

      private int filesNum_ ;
      /**
       * <pre>
       *�ļ�����
       * </pre>
       *
       * <code>int32 filesNum = 10;</code>
       */
      public int getFilesNum() {
        return filesNum_;
      }
      /**
       * <pre>
       *�ļ�����
       * </pre>
       *
       * <code>int32 filesNum = 10;</code>
       */
      public Builder setFilesNum(int value) {

        filesNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�ļ�����
       * </pre>
       *
       * <code>int32 filesNum = 10;</code>
       */
      public Builder clearFilesNum() {

        filesNum_ = 0;
        onChanged();
        return this;
      }

      private Object scanDataType_ = "";
      /**
       * <pre>
       *ɨ����������
       * </pre>
       *
       * <code>string scanDataType = 11;</code>
       */
      public String getScanDataType() {
        Object ref = scanDataType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          scanDataType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *ɨ����������
       * </pre>
       *
       * <code>string scanDataType = 11;</code>
       */
      public com.google.protobuf.ByteString
          getScanDataTypeBytes() {
        Object ref = scanDataType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          scanDataType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *ɨ����������
       * </pre>
       *
       * <code>string scanDataType = 11;</code>
       */
      public Builder setScanDataType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        scanDataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ɨ����������
       * </pre>
       *
       * <code>string scanDataType = 11;</code>
       */
      public Builder clearScanDataType() {

        scanDataType_ = getDefaultInstance().getScanDataType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ɨ����������
       * </pre>
       *
       * <code>string scanDataType = 11;</code>
       */
      public Builder setScanDataTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        scanDataType_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList filesName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFilesNameIsMutable() {
        if (!((bitField0_ & 0x00000800) != 0)) {
          filesName_ = new com.google.protobuf.LazyStringArrayList(filesName_);
          bitField0_ |= 0x00000800;
         }
      }
      /**
       * <pre>
       *�ļ���������ļ����
       * </pre>
       *
       * <code>repeated string filesName = 12;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFilesNameList() {
        return filesName_.getUnmodifiableView();
      }
      /**
       * <pre>
       *�ļ���������ļ����
       * </pre>
       *
       * <code>repeated string filesName = 12;</code>
       */
      public int getFilesNameCount() {
        return filesName_.size();
      }
      /**
       * <pre>
       *�ļ���������ļ����
       * </pre>
       *
       * <code>repeated string filesName = 12;</code>
       */
      public String getFilesName(int index) {
        return filesName_.get(index);
      }
      /**
       * <pre>
       *�ļ���������ļ����
       * </pre>
       *
       * <code>repeated string filesName = 12;</code>
       */
      public com.google.protobuf.ByteString
          getFilesNameBytes(int index) {
        return filesName_.getByteString(index);
      }
      /**
       * <pre>
       *�ļ���������ļ����
       * </pre>
       *
       * <code>repeated string filesName = 12;</code>
       */
      public Builder setFilesName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFilesNameIsMutable();
        filesName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�ļ���������ļ����
       * </pre>
       *
       * <code>repeated string filesName = 12;</code>
       */
      public Builder addFilesName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFilesNameIsMutable();
        filesName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�ļ���������ļ����
       * </pre>
       *
       * <code>repeated string filesName = 12;</code>
       */
      public Builder addAllFilesName(
          Iterable<String> values) {
        ensureFilesNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, filesName_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�ļ���������ļ����
       * </pre>
       *
       * <code>repeated string filesName = 12;</code>
       */
      public Builder clearFilesName() {
        filesName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�ļ���������ļ����
       * </pre>
       *
       * <code>repeated string filesName = 12;</code>
       */
      public Builder addFilesNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFilesNameIsMutable();
        filesName_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> files_ = java.util.Collections.emptyList();
      private void ensureFilesIsMutable() {
        if (!((bitField0_ & 0x00001000) != 0)) {
          files_ = new java.util.ArrayList<com.google.protobuf.ByteString>(files_);
          bitField0_ |= 0x00001000;
         }
      }
      /**
       * <pre>
       *����ļ�
       * </pre>
       *
       * <code>repeated bytes files = 13;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getFilesList() {
        return ((bitField0_ & 0x00001000) != 0) ?
                 java.util.Collections.unmodifiableList(files_) : files_;
      }
      /**
       * <pre>
       *����ļ�
       * </pre>
       *
       * <code>repeated bytes files = 13;</code>
       */
      public int getFilesCount() {
        return files_.size();
      }
      /**
       * <pre>
       *����ļ�
       * </pre>
       *
       * <code>repeated bytes files = 13;</code>
       */
      public com.google.protobuf.ByteString getFiles(int index) {
        return files_.get(index);
      }
      /**
       * <pre>
       *����ļ�
       * </pre>
       *
       * <code>repeated bytes files = 13;</code>
       */
      public Builder setFiles(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFilesIsMutable();
        files_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *����ļ�
       * </pre>
       *
       * <code>repeated bytes files = 13;</code>
       */
      public Builder addFiles(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFilesIsMutable();
        files_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *����ļ�
       * </pre>
       *
       * <code>repeated bytes files = 13;</code>
       */
      public Builder addAllFiles(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureFilesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, files_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *����ļ�
       * </pre>
       *
       * <code>repeated bytes files = 13;</code>
       */
      public Builder clearFiles() {
        files_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00001000);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MonitoringFile)
    }

    // @@protoc_insertion_point(class_scope:MonitoringFile)
    private static final MonitoringFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MonitoringFile();
    }

    public static MonitoringFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MonitoringFile>
        PARSER = new com.google.protobuf.AbstractParser<MonitoringFile>() {
      @Override
      public MonitoringFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MonitoringFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MonitoringFile> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MonitoringFile> getParserForType() {
      return PARSER;
    }

    @Override
    public MonitoringFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonitoringFile_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonitoringFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024MonitoringFile.proto\"\222\002\n\016MonitoringFil" +
      "e\022\020\n\010tunnelId\030\001 \001(\t\022\021\n\tgalleryId\030\002 \001(\t\022\020" +
      "\n\010siteName\030\003 \001(\t\022\025\n\rmileagePrefix\030\004 \001(\t\022" +
      "\023\n\013startLegend\030\005 \001(\t\022\021\n\tendLegend\030\006 \001(\t\022" +
      "\024\n\014numOfSection\030\007 \001(\005\022\022\n\nrectLegend\030\010 \001(" +
      "\001\022\026\n\016monitoringTime\030\t \001(\t\022\020\n\010filesNum\030\n " +
      "\001(\005\022\024\n\014scanDataType\030\013 \001(\t\022\021\n\tfilesName\030\014" +
      " \003(\t\022\r\n\005files\030\r \003(\014B\026B\024MonitoringFileEnt" +
      "ityb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MonitoringFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MonitoringFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonitoringFile_descriptor,
        new String[] { "TunnelId", "GalleryId", "SiteName", "MileagePrefix", "StartLegend", "EndLegend", "NumOfSection", "RectLegend", "MonitoringTime", "FilesNum", "ScanDataType", "FilesName", "Files", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
