spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/feign
  profiles:
    active: native
#      label: master
#      server:
#        git:
#          uri: https://gitee.com/riven666/springcloud-config.git
#          search-paths: respo
#          username: ***
#          password: ***
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#  spring.cloud.config.label：配置仓库的分支
#  spring.cloud.config.server.git.uri：配置 Git 仓库地址（GitHub、GitLab、码云 ...）
#  spring.cloud.config.server.git.search-paths：配置仓库路径（存放配置文件的目录）
#  spring.cloud.config.server.git.username：访问 Git 仓库的账号
#  spring.cloud.config.server.git.password：访问 Git 仓库的密码