spring:
  application:
    name: hello-spring-cloud-zuul
  #      服务链路追踪工程地址
  zipkin:
    base-url: http://localhost:9411
  #    服务监控和管理服务端工程地址
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign

#  自己定义服务名
#api-a:
# path: /api/a/**  访问路径  ** 匹配所有
#      path: /api/a/**
#     serviceId 对应服务消费者别名
#      serviceId: hello-spring-cloud-web-admin-ribbon
#      以 /api/a 开头的请求都转发给 hello-spring-cloud-web-admin-ribbon 服务