#spring:
#  application:
#    name: hello-spring-cloud-web-admin-feign
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#
#server:
#  port: 8765
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#feign:
#  hystrix:
#    enabled: true #开启熔断器，默认关闭

spring:
  #  分布式云配置中心地址
  cloud:
    config:
      uri: http://localhost:8888
      name: feign
      profile: dev